Migrate tel
ploomber/core pull request #2
Opened 2022-07-19 21:21 UTC by Wxl19980214

Migrate telemetry, config, and some tests here.

Small changes:
Added a if check [here](https://github.com/ploomber/core/compare/main...Wxl19980214:migrate-tel?expand=1#diff-c0500c77703069eaa61a0c9b61f11d8bc9852794558c9efcd58e0b22d993c51cR38), otherwise it kept failing locally because theres no env variable. Maybe in CI is different? But I don't think adding a check hurts.

Added a mock version [here](https://github.com/ploomber/core/compare/main...Wxl19980214:migrate-tel?expand=1#diff-c0500c77703069eaa61a0c9b61f11d8bc9852794558c9efcd58e0b22d993c51cR388). I kept failing this test because my ploomber version is the latest? Maybe we need to mock it so it is not the latest.

Changed way of importing __version__ because we are using in multiple projects. 

Also enforce a package_name parameter in log_api so that we know which package calls the telemetry.

2022-07-20 22:13 UTC, edublancas requested changes

2022-07-20 22:13 UTC, edublancas commented on setup.py
> +    'posthog',
these 3 should be in the install_requires section since they're mandatory

2022-07-20 22:13 UTC, edublancas commented on src/ploomber_core/telemetry/telemetry.py
> +    """
please add docstring documenting to document new arguments (package_name and version)

2022-07-20 22:13 UTC, edublancas commented on src/ploomber_core/telemetry/telemetry.py
> +def log_call(action, pkn, ver, payload=False):
document pkg and ver

2022-07-20 23:32 UTC, merged

2022-07-20 23:37 UTC, edublancas commented
I missed this two comments:

> Added a if check [here](https://github.com/ploomber/core/compare/main...Wxl19980214:migrate-tel?expand=1#diff-c0500c77703069eaa61a0c9b61f11d8bc9852794558c9efcd58e0b22d993c51cR38), otherwise it kept failing locally because theres no env variable. Maybe in CI is different? But I don't think adding a check hurts.

> Added a mock version [here](https://github.com/ploomber/core/compare/main...Wxl19980214:migrate-tel?expand=1#diff-c0500c77703069eaa61a0c9b61f11d8bc9852794558c9efcd58e0b22d993c51cR388). I kept failing this test because my ploomber version is the latest? Maybe we need to mock it so it is not the latest.

github is not allowing me to see this anymore, can you point me to the right files?

2022-07-21 20:29 UTC, idomic commented
@Wxl19980214 ^^